#!/usr/bin/env php
<?php

$app = require 'index.php';

use Application\Command\FourChanDash;

$console = new Symfony\Component\Console\Application();

$helpers = new \Symfony\Component\Console\Helper\HelperSet(array(
  'db' => new \Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper(
    $app['db.orm.em']['Blog']->getConnection()
  ),
  'em' => new \Doctrine\ORM\Tools\Console\Helper\EntityManagerHelper(
    $app['db.orm.em']['Blog']
  ),
));
$console->setHelperSet($helpers);
Doctrine\ORM\Tools\Console\ConsoleRunner::addCommands($console);

$console->run();
