#!/usr/bin/env php
<?php

$app = require 'index.php';

use \Symfony\Component\Console;

$console = new Console\Application();

$console->register('get')
        ->setDescription('Retrieve a config key')
        ->addArgument('key', Console\Input\InputArgument::REQUIRED, 'Which key to retrieve, using a period to denote levels')
        ->setCode(function(Console\Input\InputInterface $input,
                           Console\Output\OutputInterface $output
                          ) use ($console, $app) {
          $path = explode('.', $input->getArgument('key'));

          $yaml = \Symfony\Component\Yaml\Yaml::parse(
            $app['root_dir'] . '/data/config/config.yml'
          );

          foreach($path as $i => $key) {
            if (!isset($yaml[$key])) {
              exit(1);
            }

            if ($i == count($path) - 1) {
              $output->writeln($yaml[$key]);
              exit(0);
            }

            $yaml = $yaml[$key];
          }
        });

$console->run();
