#!/usr/bin/env php
<?php
use Application\Command\User;

$app = require 'index.php';

$console = new Symfony\Component\Console\Application();

$console->add(new User\AddAdminAccountCommand($app));
$helpers = new \Symfony\Component\Console\Helper\HelperSet(array(
  'db' => new \Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper(
    $app['db.orm.em']['User']->getConnection()
  ),
  'em' => new \Doctrine\ORM\Tools\Console\Helper\EntityManagerHelper(
    $app['db.orm.em']['User']
  ),
));
$console->setHelperSet($helpers);
Doctrine\ORM\Tools\Console\ConsoleRunner::addCommands($console);

$console->run();
